name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: windows-latest

    steps:
    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      
    - uses: actions/checkout@v4
      with:
        submodules: "recursive"
    
    - uses: suisei-cn/actions-download-file@818d6b7dc8fe73f2f924b6241f2b1134ca1377d9 # 1.6.0
      id: downloadlibs
      name: Download dependency packages
      with:
        url: "https://www.dropbox.com/s/bck09qa4csgnrqi/ck-cmd-libs-030922.7z?dl=1"
        target: ${{github.workspace}}
        
    - name: Extract packages
      run: 7z x ${{steps.downloadlibs.outputs.filename}}

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -G "Visual Studio 17 2022" -A Win32

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target ck-cmd
      
    - uses: actions/upload-artifact@v4
      with:
        name: ck-cmd-build
        path: |
          ${{github.workspace}}/build/Release
          !${{github.workspace}}/build/Release/*.lib
